### ISSUE TITLE
supporting object and dot notation 

### ISSUE THREAD

**Issue by devmondo** [abukurov/morph-expressions#6]
Hi, 

awesome work, i am just not able to use this lib because it does not support Object `{name:"hello"}` or dot notation `users[0].profile["addresses"][1]`.

thanks in advanced.

**Comment by devmondo** [comment]
thanks, i updated to the latest but the above still does not work.

**Comment by abukurov** [comment]
@devmondo You can use Square Bracket notation
```
parser.parseAndEval('users[0]["profile"]["addresses"][1]', {
  users: [{
    profile: { 
      addresses: ["foo", 'bar']
    }
  }]
}); // returns 'bar'
```

**Comment by devmondo** [comment]
@abukurov thank you very much for the support, I don't know why it did not work, maybe I had to nuke node_modules.

but still, Object is not supported? the below gives me error `unknown charecter {`
`const compiled = parser.parse('users[0]["profile"]["addresses"][1] + {name:1}');`

**Comment by abukurov** [comment]
@devmondo Yes, objects are not yet supported. `users[0]["profile"]["addresses"][1] + { name:1 }` What result are you expecting?

**Comment by abukurov** [comment]
@devmondo Now Dot notation and Square Bracket notation are fully supported
```
parser.parseAndEval('users.0.profile.addresses.1', scope)
parser.parseAndEval('users[0]["profile"]["addresses"][1]', scope)
parser.parseAndEval('users[0].profile["addresses"][1]', scope)
parser.parseAndEval('users[0].profile.addresses[1]', scope)
```

**Comment by devmondo** [comment]
@abukurov thank you again for support :)
i expect it to act same as angular-expressions https://github.com/peerigon/angular-expressions

**Comment by devmondo** [comment]
any news on this :)

**Comment by abukurov** [comment]
@devmondo You are trying to sum 2 objects in your example. I don't know what you want to get as a result. String `"[object Object]"`?

**Comment by devmondo** [comment]
@abukurov thanks for reply :) i do the following 
```
import Parser from 'morph-expressions';

const parser = new Parser();
const compiled = parser.parse('{a:1}');
console.log(compiled.eval()); // returns {a:1}
```
and i get `Unknown character '{'`
